### ISSUE TITLE
Issue on Async Running Sequence

### ISSUE THREAD

**Issue by doodlewind** [saghul/txiki.js#107]
It seems that txiki's event loop doesn't follow the microtask / macrotask concepts strictly. For example:

``` js
console.log('Hello')

setTimeout(() => console.log('!'), 0)

Promise.resolve().then(() => console.log('World'))
```

This snippet has following output in Chrome's console and `qjs`:

```
Hello
World
!
```

Since `Promise.then` returns a microtask, and if my understanding is correct, it should be executed by `JS_ExecutePendingJob` synchronously right after each eval. So the log from `Promise.then` comes before the one from `setTimeout`.

While in txiki I got following output:

```
Hello
!
World
```

Currently microtasks are triggered by `uv_check` after each tick, while after the first time we eval the script, there isn't corresponding `JS_ExecutePendingJob` calls, so the `Promise`'s microtask is kept until next tick's check phase in `setTimeout`'s macrotask, which makes the difference in running sequence.

**Comment by saghul** [comment]
Good catch! I think we could solve it by running the microtask queue also on the prepare phase. I'll take a look when I have some time. Feel free to experiment and send a PR if you find a fix. Cheers!

**Comment by doodlewind** [comment]
I try to clear the microtasks queue (execute pending jobs) manually in `TJS_Run` after the [initial eval](https://github.com/saghul/txiki.js/blob/master/src/cli.c#L298), which works for the simplest case, but not this one:

``` js
setTimeout(() => console.log('World!'), 0)
Promise.resolve().then(() => console.log('Hello'))

setTimeout(() => {
  setTimeout(() => console.log('World!'), 0)
  Promise.resolve().then(() => console.log('Hello'))
}, 1000)
```

While simply adding `JS_ExecutePendingJob` into prepare phase doesn't work neither. Wondering when is the situation that the guard in [uv__maybe_idle](https://github.com/saghul/txiki.js/blob/master/src/vm.c#L247) is supposed to work? I found it being called both in the prepare and check phases.

I'm very new to libuv but interested in this case. Since I have some time working on it, I'd love to find a PR if possible. Thanks!

**Comment by saghul** [comment]
I think I know what the problem is: prepare handles run after timer handles, so setTimeout will always "go first". The way around it would be to have our own do-while loop and run the libuv loop with UV_RUN_ONCE. Then we can call the pending jobs before uv_run and after.

Give it a shot, I'll be happy to review / provide further guidance!
