### ISSUE TITLE
imported modules go out of scope after first eval in REPL

### ISSUE THREAD

**Issue by cabrrtt** [saghul/txiki.js#109]
Having imported a module (lodash in my case), via tjs --load imports.js, the first eval in the REPL succeeds: 
_.isEqual(1,1) // true 

Repeating this throws:
TypeError: not a function

**Comment by saghul** [comment]
what does your imports.js contain?

**Comment by cabrrtt** [comment]
By using an initial eval of:
const ld = _

subsequent invocations succeed:
ld.isEqual(1,1) // true
ld.isEqual(1,1) // true

**Comment by cabrrtt** [comment]
In it simplest form, just:
import 'https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.js';

**Comment by saghul** [comment]
Your file will be imported as a module, so that variable won’t be global. You can assign it to globalThis (or window) and it should be available in the REPL.

**Comment by cabrrtt** [comment]
HI @saghul . Tried that also, and lodash is still removed from global in REPL. However, I believe the cause is simply the use of _. Here with no --load, just ./tjs

> var _ = 10
> _
undefined
> var $ = 10
> $
10

So choosing any identifier other than _, or assigning to _ with let or const is sufficient to resolve.

**Comment by cabrrtt** [comment]
Aha. _ is used in the REPL to carry the return value of the preceding eval: 
./tjs
> 1 + 1
2
> _ + 4
4

**Comment by saghul** [comment]
Right, I had totally forgotten about that :-P
