### ISSUE TITLE
Any api for reloading modules?

### ISSUE THREAD

**Issue by warvstar** [saghul/txiki.js#124]
Is there any support for module reloading? Or require support, so can use something like this? https://www.npmjs.com/package/reload

If not, what do you think the best approach would be to start implementing something like this? Thanks! Beautiful project btw.

**Comment by saghul** [comment]
Hi there! Thanks for the kind words!



> Is there any support for module reloading?

No support for that yet. 

> Or require support, so can use something like this? https://www.npmjs.com/package/reload

Nope, require is not supported, only ESM modules are. Even if require was supported, I bet there are other Node-isms txikijs doesn't support though.

What is your usecase?  The project you linked seems to be related to loading modules when accessing an app via a browser right? I'm assuming the Node app is acting as a web server then. txikijs doesn't have web server capabilities (yet) so I think it's a bit early to think about reloading :-)

Take a look at the discussion in https://github.com/saghul/txiki.js/issues/44

**Comment by warvstar** [comment]
I'm writing a game engine and I'd like to be able to reload modules as they
are modified. No networking involved in my usecase. Unloading and reloading
the whole runtime works, but to be able to reload just specific modules,
say while an infinite / game loop is running, would be awesome.

Actually I'm a noob with JavaScript, it looks like dynamic imports gets me
half way there, and its already in the js backend.

Something like this is I think what I was looking for
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.unload

**Comment by saghul** [comment]
Ah I see now!

There is no APi for it AFAIK, even at the QuickJS (the JS engine this project uses) level.

I’ll take a peek and see if I can figure something out.

**Comment by saghul** [comment]
Indeed that looks like part of what needs to be done. Right now there is no API for getting the `JSModuleDef` out of an already imported module, so that would be needed as well. Or maybe some `JS_ReloadModule` function could do it all.

This could probably be implemented as a floating patch on the QuickJS version vendored here, and then submitted upstream.

Do you want to take a crack at it?

**Comment by warvstar** [comment]
Sure thing, I'm a bit busy today but will post back here by the weekend.

In my code I just made the LoadFile method also return a JSModuleDef, and
then I keep track of those and use the unload function.

Will clean my code up a bit and post ASAP.



Indeed that looks like part of what needs to be done. Right now there is no

**Comment by saghul** [comment]
Excellent! No rush, take your time.

**Comment by saghul** [comment]
I guess this is not happening after all :-)
