### ISSUE TITLE
Windows MSVC build

### ISSUE THREAD

**Issue by gamelaster** [saghul/txiki.js#131]
Hello,

Would be possible to use MSVC for compiling binaries for Windows?

In my [QuickJS repo](https://github.com/gamelaster/QuickJS), I ported most of the things for MSVC, so it should work. [Here ](https://github.com/gamelaster/QuickJS/blob/wip/README.md) is list of things which works.

**Comment by saghul** [comment]
If your fixes land upstream, then yeah it would be worth going for it. I took a quick look at your changes and they are too big for me to maintain, and would complicate further updates, so I don't see that as a way forward as it stands now.

Then there is the dependency shenanigans. Ideally I'd like to have a statically linked binary with curl and OpenSSL in there, but that will probably take a while...

**Comment by gamelaster** [comment]
I don't think this will land into upstream, and yeah, the changes are huge.
Anyway, this was just more like question if you would be interested in this.
It's huge challenge, indeed. We will see in future, if QuickJS authors will improve win32 support.

If you want, you can keep this open, else close.
Thanks for your time

**Comment by saghul** [comment]
Thanks for understanding @gamelaster! While I'd welcome that support, we're not there yet, so let's close it for now and revisit when / if becomes a possibility.

Thank you!
