### ISSUE TITLE
Add cross compile support

### ISSUE THREAD

**Issue by topelinux** [saghul/txiki.js#139]
Could add cross compile support to make tjs could run on more platfrom

so far crossed build  target (e.g `arm`) `tjs` on X86 depends on run `qjsc` on host. For qjsc is build from `arm` in this case, which stop the next build step.

**Comment by TheBrokenRail** [comment]
When building you can set a custom QJSC with ```CUSTOM_QJSC```, so you can cross-compile.

**Comment by topelinux** [comment]
Thanks for replay
