### ISSUE TITLE
Add deno style api support for stream API

### ISSUE THREAD

**Issue by topelinux** [saghul/txiki.js#145]
For Deno and Tjs(js engine quickjs) both support ES6, Tjs actually could leverage Deno third modules(via Deno bundle
e.g Buffer(https://deno.land/x/buffer)

```bash
cat test.js
import { Buffer } from "http://deno.land/x/node_buffer/index.ts";
export { Buffer }

deno bundle test.js >buffer.js
then
tjs could just use this deno third module (with provide node style buffer)
```

The inconvenience part come when leverage http/mqtt moudle(https://deno.land/x/deno_http_server) which depends on(Deno.accept,listen, read and write), most of these API `tjs` have according implementation
For `read` the inconvenience part is that Deno use `conn.read(Buffer object)` vs `await data = conn.read([length])` 

so far i just use following WR, in js side

```js
function toDenoRead(originRead) {
    return async function(buffer) {
        return originRead(buffer.length).then((data) => {
            data.forEach((item, index) => {
                buffer[index] = item;
            });
            return data.length;
        });
    };
}

TjsDeno.connect = async function(options) {
    let {hostname, port} = options;
    const t = new tjs.TCP();

    await t.connect({ip: hostname, port});
    let originRead = t.read.bind(t);
    t.read = toDenoRead(originRead);

    return t;
}

``` 
This WR could work but not efficiently,
I think it would be great if tjs could support `Deno` style stream API natively, then user could leverage Deno modules easily in Tjs land.

**Comment by saghul** [comment]
Looks like `Deno.read` uses a `Uint8Array` now: https://doc.deno.land/builtin/stable#Deno.read so you should be able to simplify your glue code without the performance penalty of needing to iterate over the data.

**Comment by guest271314** [comment]
@topelinux Did you successfully get txiki.js to use Deno's server?

**Comment by topelinux** [comment]
> @topelinux Did you successfully get txiki.js to use Deno's server?
haven't verify with latest deno version.

**Comment by guest271314** [comment]
I am trying to get `Deno.listenTls()` working in QuickJS.
