### ISSUE TITLE
Unify pipe names on posixes and windows

### ISSUE THREAD

**Issue by c-smile** [saghul/txiki.js#150]
I believe it makes sense to unify pipe names use on Windows and Linuxes.

On all platforms pipe names are file names but having special locations. 

The function ```compose_pipe_name``` below does pipe name composition in platform independent manner.

And so updated tjs_pipe_connect and tjs_pipe_bind:

```c
static char* compose_pipe_name(const char* logical_pipe_name, char* buf, size_t len)
{
#ifdef _WIN32
  strcpy(buf, "\\\\.\\pipe\\");
  strncat(buf, logical_pipe_name, len - 10);
#else
  strcpy(buf,"/tmp/");
  strncat(buf, logical_pipe_name, len - 6);
#endif
  return buf;
}

static JSValue tjs_pipe_connect(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    TJSStream *t = tjs_pipe_get(ctx, this_val);
    if (!t)
        return JS_EXCEPTION;

    const char *name = JS_ToCString(ctx, argv[0]);
    if (!name)
        return JS_EXCEPTION;

    TJSConnectReq *cr = js_malloc(ctx, sizeof(*cr));
    if (!cr) {
        JS_FreeCString(ctx, name);
        return JS_EXCEPTION;
    }
    cr->req.data = cr;

    char buf[512];

    uv_pipe_connect(&cr->req, &t->h.pipe, compose_pipe_name(name,buf,countof(buf)), uv__stream_connect_cb);

    JS_FreeCString(ctx, name);

    return TJS_InitPromise(ctx, &cr->result);
}

static JSValue tjs_pipe_bind(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    TJSStream *t = tjs_pipe_get(ctx, this_val);
    if (!t)
        return JS_EXCEPTION;

    const char *name = JS_ToCString(ctx, argv[0]);
    if (!name)
        return JS_EXCEPTION;

    char buf[512];

    int r = uv_pipe_bind(&t->h.pipe, compose_pipe_name(name, buf, countof(buf)));
    if (r != 0)
        return tjs_throw_errno(ctx, r);

    return JS_UNDEFINED;
}
```

**Comment by saghul** [comment]
I kindly disagree :-) It's a slippery slope. Pipes are just files on Unix (let's ignore abstract sockets) so chasing the path just because is very unexpected.

**Comment by c-smile** [comment]
Well, libuv is not just about Linux.  

In any case it makes sense to enforce use of /tmp for pipes.  Usually /tmp is mounted on tmpfs (backed by virtual memory). and a reboot will empty /tmp . 

On Windows pipe names are file names (not paths) that MUST be created under \\.\pipe\ , see: https://docs.microsoft.com/en-us/windows/win32/ipc/pipe-names.  So I think it makes sense to treat/handle pipe names as plain name tokens to makes this work uniformly across different platforms.

**Comment by saghul** [comment]
I know quite a bit  about libuv.

You are tying to create an abstraction that doesn't make sense INHO.

Usage of pipes on Windows is really not common, and as something very platform specific, it should be up to whoever writes the application to decide.

In you sample code you'd be ignore if the users desire if they pass an absolute path for example.

That said, a utility method that given a bare pipe name builds one on /tmp would be acceptable, but not as the default behavior. Applications should be able to open pipes where they please.
