### ISSUE TITLE
bug report: these two lines are not necessary and will cause leak

### ISSUE THREAD

**Issue by fatfatson** [saghul/txiki.js#161]
https://github.com/saghul/txiki.js/blob/cb3ab9cd09f3ed51dc6e4757dd904642052471eb/src/utils.c#L186

**Comment by saghul** [comment]
Can you make a PR? I remember I struggled to get this one right because otherwise there were leaks. Tests run in debug mode, so if there is a leak there would be a crash.

**Comment by fatfatson** [comment]
I think about it again
under the current mechanism, it is reasonable to dup the two functions here
But the problem is that the current mechanism does not meet my two needs
1. If I don't save the socket object, it should not be GC (when the connection is active), but if the connection is broken, then the socket and its promise should be recycled
2. before I exit the program, I will close all libuv connections, and the corresponding quickjs object should be recycled automatically, so as not to trigger assert

**Comment by saghul** [comment]
Do you have a code snippet that doesn't work the way you expect?

**Comment by saghul** [comment]
No follow-up, closing.
