### ISSUE TITLE
sys.fs.watch() implementation.

### ISSUE THREAD

**Issue by c-smile** [saghul/txiki.js#162]
Please consider adding this sys.fs.watch() implementation:
https://github.com/c-smile/txiki.js/commit/517f7962da743b39869efed5b8ae450cc07d0b58

It adds two functions: 

-  [sys.fs.watch()](https://github.com/c-smile/txiki.js/blob/master/doc/sys.fs.watch.md)
-  [sys.fs.splitpath()](https://github.com/c-smile/txiki.js/blob/master/doc/sys.fs.splitpath.md)

**Comment by saghul** [comment]
Can you please send a PR with each change? dirname and basename are already implemented here: https://github.com/saghul/txiki.js/blob/master/src/js/path.js FWIW.

**Comment by c-smile** [comment]
That `dirname` and `basename` you mentioned will not work correctly on Windows paths.

**Comment by saghul** [comment]
Then a PR would be most welcome! :-)
