### ISSUE TITLE
Update Wasm3, make use of exciting new API

### ISSUE THREAD

**Issue by vshymanskyy** [saghul/txiki.js#165]
With latest Wasm3 (master branch), new API is available which fixes many things in the public API:
- Exported function signature introspection
- Introspection of imported functions (see `context` argument)
- Public api for calls with raw arguments (instead of strings)
- Public API to get return values
- Support recursive `m3_Call` invocation. I.e. calling exported function from within imported function callback.
- `m3_RunStart` can be used to force the module initialization.

I think all this can greatly help **txiki.js** implementation. Let me know it you need any other public API, or have any ideas!

This is already implemented in Python bindings, you can use it as a reference:
https://github.com/wasm3/wasm3/blob/master/platforms/python/m3module.c
Tests (in Python):
https://github.com/wasm3/wasm3/blob/master/platforms/python/test/test_m3.py

**Comment by vshymanskyy** [comment]
@saghul , the `0.4.9` is now available: https://github.com/wasm3/wasm3/releases/latest

**Comment by saghul** [comment]
Nice! I'll take a look, I've been wanting to do this for a while!

**Comment by saghul** [comment]
It's ready in https://github.com/saghul/txiki.js/pull/171 but I get some very weird crashes when building in Debug mode: https://github.com/wasm3/wasm3/issues/269
