### ISSUE TITLE
readFile('/dev/stdin') 

### ISSUE THREAD

**Issue by jedahan** [saghul/txiki.js#170]
I could not read `/dev/stdin` with the fs.readFile call, so I had to write my own. Is this intended behavior?

```shell
$ echo hithere | tjs readfile.js
hithere

Unhandled promise rejection: Error: invalid seek
    at <anonymous> (readfile.js:18)
```

```js
#!tjs
async function readFile(filename='/dev/stdin') {
  const buffer = new ArrayBuffer(1024)

  const handle = await tjs.fs.open(filename, 'r')
  let string = ''
  let data = await handle.read(buffer.length)
  while (data.length) {
    string += new TextDecoder().decode(data)
    data = await handle.read(buffer.length)
  }
  return string
}

(async () => {
  console.log(await readFile('/dev/stdin')) 
  console.log(await tjs.fs.readFile('/dev/stdin'))
})()
```

**Comment by saghul** [comment]
That is intended behavior, yes. readFile reads regular files, and /dev/stdin isn't one of them. You can't seek it until the end for example, which is what we do to get the size.

What you did is correct.

**Comment by jedahan** [comment]
Running this snippet on the latest version of tjs gives:

```
Unhandled promise rejection: TypeError: not a TypedArray
at readFile (src/web/render.js:6)
```

From this project https://github.com/jedahan/kiss-find/blob/main/src/web/render.js

Any suggestions on where to look? Should I not be using an ArrayBuffer?

**Comment by jedahan** [comment]
Thanks for the quick response. Works now. Next time I'll pin my dependencies to a particular commit too and only intentionally upgrade :)
