### ISSUE TITLE
Top level await

### ISSUE THREAD

**Issue by TheNoim** [saghul/txiki.js#175]
Hi,

One killer feature for simple scripting could be [top level await](https://github.com/tc39/proposal-top-level-await). 

Currently, top level await isn't supported by either quickjs or txiki.js, I can't tell for sure.

**Comment by saghul** [comment]
It's QuickJS. Once it gains support for it I'll update the dependency and txiki.js will have it too.

**Comment by brandonros** [comment]
What is the proper way to wait for a Promise to resolve/reject from an `eval` context in the mean time?

**Comment by saghul** [comment]
Fixed in https://github.com/saghul/txiki.js/pull/362
