### ISSUE TITLE
Add cryptographic operations with libsodium

### ISSUE THREAD

**Issue by saghul** [saghul/txiki.js#275]
Check how mush of the WebCrypto API can be implemented with it.

**Comment by bnoordhuis** [comment]
Not much. libsodium is very much built around the principle of "there's only one way to do it" so there's only one way to hash, one way to encrypt, etc. WebCrypto on the other hand is a smorgasbord of hashes, ciphers, and so on.

**Comment by saghul** [comment]
I was thinking about having something like a minimal WebCrypto of sorts. Not too keen on wrapping OpenSSL :-P
