### ISSUE TITLE
What is wrong with WebAssembly

### ISSUE THREAD

**Issue by UserFive5** [saghul/txiki.js#280]
WebAssembly Is A good move in this project but I think it's too limited and hard to deal with . so i think is it better to use ffi to make things easy and quick
. Thanks man - this is the best project I found since programming in JavaScript

**Comment by saghul** [comment]
Thanks for the kind words!

Nothing wrong with WASM IMHO, just another web API and integrating wasm3 was fun and gave me some insight as to how WASM actually works.

I need to find some time for integrating one of the existing QuickJS FFI projects, but haven't had much lately...

**Comment by saghul** [comment]
Yep, that's another way to go about it. I experimented with that some time ago here: https://github.com/saghul/wasi-lab/tree/master/qjs-wasi

**Comment by adminy** [comment]
I was thinking of https://github.com/wasm3/wasm3 when I said that but it should all be the same right? Thanks for the reference, I'll give it a try.

**Comment by saghul** [comment]
FFi support just landed in master.

**Comment by UserFive5** [comment]
Amazing, The Project Have Really Grown Up.
