### ISSUE TITLE
ReferenceError: could not load '@jsany/aw'

### ISSUE THREAD

**Issue by daolou** [saghul/txiki.js#295]
![image](https://user-images.githubusercontent.com/22312092/168766905-2ca0be96-7a8d-4e6d-a24e-3b23f653e0bd.png)

dist/index.js: 

```js
import aw from '@jsany/aw'

aw.log('test')
```

exec `./node_modules/@jsany/aw/runtime/tjs ./dist/index.js`, then output:

```sh
 ReferenceError: could not load '@jsany/aw'
```

**Comment by saghul** [comment]
txiki.js does not currently look in node_modules when resolving imports. It acts as a browser.

**Comment by daolou** [comment]
thx
