### ISSUE TITLE
TextDecoder().decode() pollyfill performance issue

### ISSUE THREAD

**Issue by samuelbrian** [saghul/txiki.js#316]
Since changing from the `text-encoding` pollyfill to `text-encoding-utf-8` (in https://github.com/saghul/txiki.js/pull/311), the performance of text decoding has dropped significantly.

In my testing, it was taking over 3 seconds to read a 175kb file and decode it into a JS string. It does depends on the size of the chunk you're giving to the text decoder.

Part of the problem is that the decoding routine in `text-encoding-utf-8` examines each byte in the input buffer, it shifts the byte from the start ([see the Stream class here](https://github.com/arv/text-encoding-utf-8/blob/master/src/encoding.js#L160)) .
The original `text-encoding` does this better ([see the Stream class here](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js#L194)) by reversing the input buffer and operating on the end of the buffer rather than the start.

I've applied the reversing changes to `text-encoding-utf-8` (in https://github.com/samuelbrian/txiki.js/commit/99b895c9c5ba0cbaeee8bb1f96af9a0ce2d5a4df) and it's seems on-par with the original version. But I'm not sure the best way to manage patching the node_modules dependencies, short of forking and maintaining a copy of `text-encoding-utf-8`.

Even better is using text encoding and decoding from QuickJS which I have done here https://github.com/samuelbrian/txiki.js/commit/f308a6dd6a64ae8a36d108e2bbdf822f5d6f7f3f, and that makes a file read that was taking >3 seconds into a <1 millisecond operation.
I've exposed these as tjs functions rather than implement them as TextEncoder/TextDecoder and remove the pollyfill, mainly because I didn't want to have to deal with the streaming option. But it might be viable to do.

**Comment by saghul** [comment]
Good analysis, thanks!

How about this: implement our own TextDecoder polyfill using the C functions you created under the hood.

Did the original one support streaming? I didn't think it did...

**Comment by samuelbrian** [comment]
The original and UTF-8-only pollyfills do support streaming. I'm relying on it right now to decode while reading single bytes from raw mode stdin.

I think to correctly handle streaming, ignoreBOM, and fatal, it'd have to go deeper and use QuickJS's `unicode_to_utf8()` and `unicode_from_utf8()`.

**Comment by saghul** [comment]
Oh I see.

So another approach is to go the patch-package route. We can patch a Node module at install time (see the patches directory) and either fix the current dep or revert back and slash other encodings?

**Comment by saghul** [comment]
Fixed in https://github.com/saghul/txiki.js/pull/321
