### ISSUE TITLE
can this work on openwrt / mips ?

### ISSUE THREAD

**Issue by dberardo-com** [saghul/txiki.js#317]
i am trying to let javascript run on an openwrt installation, and thought of using txiki.

i am able to run wasm3 compiler from the official doc, running the benchmark and also the WASI test. but i am not managing to compile "make" this txiki.

i am not using a 32/64 bit architecture, so can this work?

here my error log:

```
Error relocating /usr/bin/make: __dlsym_time64: symbol not found
Error relocating /usr/bin/make: __lstat_time64: symbol not found
Error relocating /usr/bin/make: __localtime64: symbol not found
Error relocating /usr/bin/make: __gettimeofday_time64: symbol not found
Error relocating /usr/bin/make: __fstat_time64: symbol not found
Error relocating /usr/bin/make: __ctime64: symbol not found
Error relocating /usr/bin/make: __stat_time64: symbol not found
Error relocating /usr/bin/make: __pselect_time64: symbol not found
Error relocating /usr/bin/make: __time64: symbol not found
Error relocating /usr/bin/make: __clock_gettime64: symbol not found

```

**Comment by saghul** [comment]
I think it should work, but it might need some tweaks. Can you provide some instructions on how to try and do this, maybe with quemu?

**Comment by dberardo-com** [comment]
i am not familiar with these kinds of technologies. what is quemu?

i could provide you information on the cpu/OS if that could help you ?

**Comment by saghul** [comment]
No worries. quemu is a virtualization tool, so one can emulate a MIPS processor and try building it there: https://www.qemu.org/

Also, just to clarify: what component fails to build? Is it just wasm3?

**Comment by bnoordhuis** [comment]
Just a note: the error message says `make` has relocation errors, not txiki. It's a toolchain issue.

**Comment by dberardo-com** [comment]
no no, i am sorry. Wasm3 has already been installed from this page using this binary `wasm3-linux-mipsel-24kc-sf `: https://github.com/wasm3/wasm3-openwrt-packages/releases

that works fine for WASI and other wasm files, like with coremark.wasm:

```bash
$ /wasm3-linux-mipsel-24kc-sf coremark.wasm

2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 2044330016
Total time (secs): 19.224199
Iterations/Sec   : 57.219549
Iterations       : 1100
Compiler version : Clang 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
Compiler flags   : -O3
Memory location  : STATIC
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x33ff
Correct operation validated. See README.md for run and reporting rules.
CoreMark 1.0 : 57.219549 / Clang 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06) -O3    / STATIC
``` 
---
I had no `make` installed on the device, so i used: `opkg install make` to install it and then follow the README of this project to build txiki, then the error posted above.

it seems, like you said, an error of the make installation, because even outside the txiki dir, i get this error:
```bash
$ opkg install make
Package make (4.3-1) installed in root is up to date.
$ make --version
Error relocating /usr/bin/make: __dlsym_time64: symbol not found
Error relocating /usr/bin/make: __lstat_time64: symbol not found
Error relocating /usr/bin/make: __localtime64: symbol not found
Error relocating /usr/bin/make: __gettimeofday_time64: symbol not found
Error relocating /usr/bin/make: __fstat_time64: symbol not found
Error relocating /usr/bin/make: __ctime64: symbol not found
Error relocating /usr/bin/make: __stat_time64: symbol not found
Error relocating /usr/bin/make: __pselect_time64: symbol not found
Error relocating /usr/bin/make: __time64: symbol not found
Error relocating /usr/bin/make: __clock_gettime64: symbol not found
```

**Comment by saghul** [comment]
Oh. That looks like the `make` package is somehow broken in that environment!

**Comment by dberardo-com** [comment]
ok, i will have a look at how to fix this. will it work with make or must it be cmake? 

do you know of any alternative build tool that can do the job too?

**Comment by saghul** [comment]
cmake is a meta-builder, you end up needing make (or ninja) in the end, so I'd say that would need to be sorted out first.
