### ISSUE TITLE
Implement localStorage and sessionStorage

### ISSUE THREAD

**Issue by saghul** [saghul/txiki.js#346]
localStorage would be implemented using a file inside TJS_HOME.

NOTE: These are not available in a worker context.

**Comment by Gary-Hobson** [comment]
Maybe use [unqlite](https://github.com/symisc/unqlite) to implement localStorage
unqlite is a nosql KV database, using it to implement localStorage will be simpler and more efficient

**Comment by saghul** [comment]
Fixed in https://github.com/saghul/txiki.js/pull/408 -- currently using SQLite internally.
