### ISSUE TITLE
Add typescript declaration file ?

### ISSUE THREAD

**Issue by partic2** [saghul/txiki.js#348]
How about adding typescript declaration?  IMHO it's helpful when code with IDE.

**Comment by saghul** [comment]
Like this one? https://github.com/saghul/txiki.js/blob/master/docs/txikijs.d.ts

Maybe it should be located elsewhere so it's picked up?

**Comment by partic2** [comment]
Yes,This is just what I want, Thanks. 

I neglected docs directory and forgot to use search tool.
