### ISSUE TITLE
fetch() from browser net::ERR_INVALID_HTTP_RESPONSE when testing tjs.listen()

### ISSUE THREAD

**Issue by guest271314** [saghul/txiki.js#353]
Command line `$ ./tjs run ../tests/test-tcp.js`

```
import { assert } from '@tjs/std';

const encoder = new TextEncoder();
const decoer = new TextDecoder();


async function doEchoServer(server) {
    const conn = await server.accept();
    conn.setKeepAlive(true);
    conn.setNoDelay(true);
    console.log(server);
    if (!conn) {
        return;
    }

    const buf = new Uint8Array(4096);
    while (true) {
        const nread = await conn.read(buf);
        if (nread === null) {
            break;
        }
        conn.write(buf.slice(0, nread));
    }
}

(async () => {
    const server = await tjs.listen('tcp', '0.0.0.0', '8000');

    console.log(server);
    doEchoServer(server);
})();
```

Browser

```
fetch('http://localhost:8000', {method:'post', body:JSON.stringify('Test')})
.then(async (r) => {
  console.log(await r.text());
})
.catch(console.error);
```
```
fetch('http://localhost:8000?test=123')
.then(async (r) => {
  console.log(await r.text());
})
.catch(console.error);
```

**Comment by saghul** [comment]
The error is correct, your server does not send a valid HTTP response.

**Comment by guest271314** [comment]
That is the example TCP server in this repository. Is that example TCP server not expected to send a valid HTTP response? Do any of the example servers send a valid HTTP response? Where can we set headers?

**Comment by saghul** [comment]
It's a TCP server, not an HTTP server. I'm not sure I could have used a clearer name.

If you want to create an HTTP server then you'll need to build one yourself, I don't have one built already, sorry.

**Comment by guest271314** [comment]
> It's a TCP server, not an HTTP server. I'm not sure I could have used a clearer name.

This https://github.com/WICG/direct-sockets/issues/46 _might_ work to connect to the TCP server from the browser. There are some specific steps that must be taken to do that https://github.com/WICG/direct-sockets/issues/46#issuecomment-1093313336.

Does txiki.js currently support creating a WebSocket server?

**Comment by saghul** [comment]
Not currently , just WebSocket client is supported.
