### ISSUE TITLE
utils.js is not found in build

### ISSUE THREAD

**Issue by guest271314** [saghul/txiki.js#354]
- [examples/echo-server-udp.js](https://github.com/saghul/txiki.js/blob/31ce61a0674906ff7ac5b1f3ee0bdfc935f17424/examples/echo-server-udp.js)
- [examples/echo-client.js](https://github.com/saghul/txiki.js/blob/e7ea3961032c6d40fac6fd938e746746e6d6f3ff/examples/echo-client.js)
- - [examples/echo-server.js](https://github.com/saghul/txiki.js/blob/e7ea3961032c6d40fac6fd938e746746e6d6f3ff/examples/echo-server.js)

**Comment by saghul** [comment]
It's here: https://github.com/saghul/txiki.js/blob/master/examples/utils.js are you getting an import error?

**Comment by guest271314** [comment]
Built again. The file is there.
