### ISSUE TITLE
Support Uint32Array, other TypedArray's and ArrayBuffer parameter for stdin.read() (StdioInputStream))

### ISSUE THREAD

**Issue by guest271314** [saghul/txiki.js#369]
Native Messaging protocol sends length of payload before payload, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#app_side; and this answer on StackOverflow https://stackoverflow.com/a/26140545.

> Each message is serialized using JSON, UTF-8 encoded and is preceded with an unsigned 32-bit value containing the message length in native byte order.

When using txiki.js as a Native Messaging host, we need to convert the `Uint8Array` to a `Uint32Array` to get the message length. 

The following works as expected for reading input as JSON until I pass `new Array(13107)` to the host, which should be `65536` `JSON.stringify(new Array(13107)).length` the resulting calculated length is greater than expected, resulting in the application freezing the OS - when running on RAM only on a live system. The `Uint8Array` should not be freezing the system running txiki.js.  

In pertinent part

```
  let encoder = new TextEncoder();
  let decoder = new TextDecoder();

  async function getMessage() {
    const buffer = new ArrayBuffer(4);
    const header = new Uint8Array(buffer);
    const input = await tjs.stdin.read(header);
    const u32 = new Uint32Array(buffer);
    // https://stackoverflow.com/a/26140545
    const length = new Uint32Array(header.buffer).reduce(
      (a, b, index) => a | (b << (index * 8)),
      0
    );
    
    const f = await tjs.open('message_length.txt', 'w');
    await f.write(encoder.encode(JSON.stringify({header, length, u32})));
    const output = new Uint8Array(length);
    await tjs.stdin.read(output);
    return output;
  }
```

In QuickJS we can read to a `TypedArray` other than `Uint8Array`, and successfully get the maximum payload (1MB) back from the Native Messaging host per the protocol (`new Array(209715)`, `JSON.stringify(new Array(209715)).length // 1048576`)

```
function getMessage() {
  const header = new Uint32Array(1);
  std.in.read(header.buffer, 0, 4);
  const output = new Uint8Array(header[0]);
  std.in.read(output.buffer, 0, output.length);
  return output;
}
```

**Comment by saghul** [comment]
> When using txiki.js as a Native Messaging host, we need to convert the `Uint8Array` to a `Uint32Array` to get the message length.

You can use a DataView over the backing ArrayBuffer, no copy necessary. 

> The following works as expected for reading input as JSON until I pass `new Array(13107)` to the host, which should be `65536` `JSON.stringify(new Array(13107)).length` the resulting calculated length is greater than expected, resulting in the application freezing the OS - when running on RAM only on a live system. The `Uint8Array` should not be freezing the system running txiki.js.

Not sure I understand the problem here. I don't think that length is deterministic since it depends on the numbers in the array, doesn't it? Even so, how exactly does the OS freeze?

MIght be important to know what type of stdin you are working with, what does `tjs.stdin.type` return?

**Comment by guest271314** [comment]
> You can use a DataView over the backing ArrayBuffer, no copy necessary.

I tried `DataView` and the `getUint32()` method on the buffer to no avail.

> Not sure I understand the problem here. I don't think that length is deterministic since it depends on the numbers in the array, doesn't it? 

The length of the message can be up to 4GB. This is the protocol https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-protocol.

I don't think the rand of 0-255 of a `Uint8Array` is designed to handle the case where length is equal to or greater than 65536. If you know how to represent 65536 and greater in 4 bytes

> The same format is used to send messages in both directions: each message is serialized using JSON, UTF-8 encoded and is preceded with 32-bit message length in native byte order

set in a `Uint8Array` that is equivalent  kindly share that.

> Even so, how exactly does the OS freeze?

The mouse stops working. CTRL+ALT+F2 doesn't work. I had to reboot the machine several time during testing. Since I'm running a live CD using only RAM that means I lose all my work. Only a couple time sending an interrupt by way of power manager configuration that asks what to do when power button is pressed was I able to get the system back without rebooting.

I can provide you with the exact steps to reproduce if you are willing to reproduce the issue yourself. I can successfully process input of 1MB and echo that output back to the client using QuickJS, Deno, Node.js, Bun (in JavaScript engines) which each are capable of writing stdin to a buffer other than `Uint8Array`; I also have done the same in C, C++, Python and WASI/WebAssembly.

> MIght be important to know what type of stdin you are working with, what does tjs.stdin.type return?

pipe.

**Comment by guest271314** [comment]
Does `tjs.stdin.read()` support reading 65536 or greater into a `Uint8Array`?

**Comment by guest271314** [comment]
To reproduce follow these instructions https://github.com/guest271314/native-messaging-nodejs (or https://github.com/guest271314/native-messaging-webassembly).

Substitute this code for nm_node.js, name the file nm_tjs.js and make sure the `"short_name"` in manifest.json is `"nm_tjs"`.

You'll notice I send 1MB  `port.postMessage(new Array(209715))` to the host in background.js in the repositories above and here https://github.com/guest271314/native-messaging-deno, https://github.com/guest271314/native-messaging-bun, https://github.com/guest271314/native-messaging-quickjs, https://github.com/guest271314/native-messaging-c, https://github.com/guest271314/native-messaging-cpp, https://github.com/guest271314/native-messaging-python. Use 

```
port.postMessage(new Array(13106));
```

for txiki.js version and `port.postMessage(new Array(13107))` for the txiki.js version to break.

```
#!/usr/bin/env -S ./tjs run
// txiki.js Native Messaging host
// guest271314, 5-6-2022
(async () => {

  let encoder = new TextEncoder();
  let decoder = new TextDecoder();

  async function getMessage() {
    // const buffer = new Uint32Array(4);
    const header = new Uint8Array(4);
    const input = await tjs.stdin.read(header);
    
    const u32 = new Uint32Array(header.buffer);
    // https://stackoverflow.com/a/26140545
    const length = new Uint32Array(header.buffer).reduce(
      (a, b, index) => a | (b << (index * 8)),
      0
    );
    const view = new DataView(header.buffer);
    const viewLength = view.getUint32(0);
    /*
    const readBuf = new Uint8Array(1);
    const buf = [];
    let p = 0;
    while (true) {
        const n = await tjs.stdin.read(readBuf);
        ++p;
        if (n === null) {
            break;
        }

        buf.push(...readBuf.subarray(0, n));
    }
    */
    let output = new Uint8Array(length);
    const read = await tjs.stdin.read(output);
    const f = await tjs.open('message_length.txt', 'w');
    await f.write(encoder.encode(JSON.stringify({header, input, length, u32, viewLength})));
    await f.close();
    return output;
  }

  async function sendMessage(message) {
    // https://stackoverflow.com/a/24777120
    const header = Uint32Array.from(
      {
        length: 4,
      },
      (_, index) => (message.length >> (index * 8)) & 0xff
    );
    const output = new Uint8Array(header.length + message.length);
    output.set(header, 0);
    output.set(message, 4);
    await tjs.stdout.write(output);
    return true;
  }

  while (true) {
    const message = await getMessage();
    await sendMessage(message);
})();
```

**Comment by guest271314** [comment]
I located the exact breaking point - the OS will freeze, though I was able to interrupt and regain control of the machine and log the result.

When we pass `new Array(13107)` we get the expected result.

When we pass `new Array(13108)` we do not get the expected result.

```
{
"header":{"0":251,"1":255,"2":0,"3":0},
"input":4,
"length":65531,
"outputLength":65531,
"u32":{"0":65531},
"viewLength":4227792896
}
```

```
{
"header":{"0":117,"1":108,"2":108,"3":44},
"input":4,
"length":745303157,
"u32":{"0":745303157},
"viewLength":1970039852
}
```

**Comment by guest271314** [comment]
Solved.

`tjs.stdin.read()` is not guaranteed to read the full length of the `Uint8Array` passed with one call. It reads less than 65536.

I adapted the code from https://github.com/saghul/txiki.js/blob/e7ea3961032c6d40fac6fd938e746746e6d6f3ff/src/js/core/tjs/eval-stdin.js

```
async function readFullAsync(length) {
  const readBuf = new Uint8Array(65536);
  const buf = [];
  while (buf.length < length) {
    const n = await tjs.stdin.read(readBuf);
    if (n === null) {
      break;
    }
    buf.push(...readBuf.subarray(0, n));
  }
  return new Uint8Array(buf);
}

async function getMessage() {
  const header = new Uint8Array(4);
  const input = await tjs.stdin.read(header);
  const [length] = new Uint32Array(header.buffer,header.byteOffset,header.byteLength / Uint32Array.BYTES_PER_ELEMENT);
  const output = await readFullAsync(length);
  return output;
}
```

**Comment by saghul** [comment]
Glad to hear!
