### ISSUE TITLE
Could this be used on an e.g. Pico Pi?

### ISSUE THREAD

**Issue by serapath** [saghul/txiki.js#384]
Was wondering if a small web server on a Pico Pi would be a good use case to tinker around :-)

**Comment by saghul** [comment]
I don't think so, since it doesn't run Linux, does it?

It would run on a W for sure...

**Comment by CanadaHonk** [comment]
@serapath Have a look at [DeviceScript](https://microsoft.github.io/devicescript) (made for microcontrollers like the RPi Pico), it has support for the RP2040 and is TypeScript-y.
