### ISSUE TITLE
[Question] Making JS Files a Built-in module

### ISSUE THREAD

**Issue by cemalgnlts** [saghul/txiki.js#386]
I've studied your project for a long time, I don't know C, I couldn't understand it completely, so I have a few questions (I hope you can help).

I asked this question on [bellard/quickjs](https://github.com/bellard/quickjs/issues/185) and on [StackOverflow](https://stackoverflow.com/questions/76455228/quickjs-translate-a-module-created-with-js-to-c-and-use-it-as-a-builtin-module) then i found your project.

In QucikJS, `console` only supports `log`, so you added this code to extend it: [src/js/polyfills/console.js](https://github.com/saghul/txiki.js/blob/master/src/js/polyfills/console.js)

You are importing all the JS code in the entire `polyfills` folder, including `console.js`, into the `polyfills.js` file.

https://github.com/saghul/txiki.js/blob/6439949ecbabd92b0c05d63f3c9d155938b548ed/Makefile#L15-L23

Then you convert the resulting `polyfills.js` file into `polyfills.o` code using `qjsc`.
https://github.com/saghul/txiki.js/blob/6439949ecbabd92b0c05d63f3c9d155938b548ed/Makefile#L25-L31

All good so far, but I missed the later part of how you included the `polyfills.o` files.

**Comment by saghul** [comment]
> Then you convert the resulting `polyfills.js` file into `polyfills.o` code using `qjsc`.

Not quite, this generates a polyfills.c file, it's C source code, basically an array with the JS bytecode.

It's included in the build here: https://github.com/saghul/txiki.js/blob/6439949ecbabd92b0c05d63f3c9d155938b548ed/CMakeLists.txt#L87

So it gets compiled with the rest of the binary.

**Comment by cemalgnlts** [comment]
I was thinking that the `-c` flag is needed to convert to C code.

> -c
Only output bytecode in a C file. The default is to output an executable file.

https://bellard.org/quickjs/quickjs.html#qjsc-compiler

**Comment by saghul** [comment]
> I was thinking that the `-c` flag is needed to convert to C code.

Correct, it outputs a C file. You can see it here: https://github.com/saghul/txiki.js/blob/master/src/bundles/c/core/run-main.c

**Comment by cemalgnlts** [comment]
When I convert a JS file to C, all its dependencies are also included in C. How did you avoid this?

I have two libraries:
- `lib-A.js`
- `lib-B.js`

`lib-A.js` needs `lib-B.js`.

When I compile, the `lib-A.c` file contains both its own code and `lib-B.js`, while `lib-B.c` contains only its own code. 

__It's actually normal, but it's causing problems with it.__

I can avoid this like this: I create `index.js` file and import it into two files so I have a single `module.c` file that contains both `lib-A.js` codes and `lib-B.js` codes.

The minus side of this is that index.js codes that will not be used will be added and the resulting C file will be large.

**Comment by cemalgnlts** [comment]
Understood thanks, you've been very helpful.
