### ISSUE TITLE
@types packet for txikijs

### ISSUE THREAD

**Issue by lal12** [saghul/txiki.js#390]
I would propose creating `@types/txikijs` npm package containing the txikijs.d.ts, if they are allow. Haven't looked into their guidelines yet.

Alternatively creating just a `txikijs-types` package, but this isn't picked up by default and needs an import.

Could do a PR and publish it, depending on what you want @saghul ?

**Comment by saghul** [comment]
Sounds good! Perhaps @txikijs/types would make sense?

**Comment by lal12** [comment]
I looked into it a bit more, while DefinitelyTyped (`@types/*` packages) would be the easiest (`npm install` & done) solution, it would either require to maintain definitions in their repo or to sync it, but this most likely not worth the hassle.

So I am doing a PR with a new package, this then can be imported `import type from '@types/txikijs';` or specified in the `typeRoots` property in `tsconfig.json`

**Comment by lal12** [comment]
See #391
