### ISSUE TITLE
tjs do not show any error message when import failed

### ISSUE THREAD

**Issue by topelinux** [saghul/txiki.js#405]
when import an no exist module from tjs, tjs just exit without show any hint

e.g.
test.js
```javascript
mport {no} from "no.js"
```
tjs run test.js
just exit without show any hint for debug.

the reason is that in "src/js/run-main/index.js"
currently it only handle SyntaxError
``` javascript
            // execution of the file results in an exception... :-(
            globalThis.queueMicrotask(() => {
                try {
                    internals.core.evalFile(filename);
                } catch (e) {
                    if (e instanceof SyntaxError) {
                        console.error(e);
                    }
                    tjs.exit(1);
                }
```

**Comment by saghul** [comment]
Ouch. What error is thrown in that case?

**Comment by topelinux** [comment]
error is ReferenceError: could not load 'no.js'
    at evalFile (native)
    at <anonymous> (run-main.js)
