### ISSUE TITLE
This is weak

### ISSUE THREAD

**Issue by jimmywarting** [saghul/txiki.js#430]
- [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry)
- <s>[WeakSet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet)</s>
- <s>[WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)</s>
- WeakRef

They are very fundamental and also quite important for also AbortController / AbortSignal (to not leak memory among other things)
They are impossible to polyfill cuz they need to be handled on a much lower level where GC happens.

**Comment by saghul** [comment]
The first one needs to be implemented in QuickJS, but the last 2 are there already.

The weak set/map support is kinda specific in QuickJS right now so adding WeakRef and the registry may take a bit...

**Comment by jimmywarting** [comment]
Oh, i also forgot WeakRef

**Comment by saghul** [comment]
Let's continue here, which is there support needs to happen: https://github.com/quickjs-ng/quickjs/issues/54

**Comment by saghul** [comment]
WeakRef landed: https://github.com/quickjs-ng/quickjs/pull/148

**Comment by saghul** [comment]
So did FinalizationRegistry :-)
