### ISSUE TITLE
std.loadscript() equivalent 

### ISSUE THREAD

**Issue by ClosetGeek-Git** [saghul/txiki.js#449]
Does txiki.js have the equivalent of quickjs's std.loadscript()?

**Comment by saghul** [comment]
What do you need it for? Why not import a module directly? Or are you using the REPL?

**Comment by ClosetGeek-Git** [comment]
I’m currently experimenting with tjs run. Std.loadscript() is able to load scripts that would typically be in a html <script> tag, for example babel-standalone.

**Comment by saghul** [comment]
Sorry I might be a bit obtuse but I still don't get the use case.

There is no HTML here, so you can write a script that imports another.

Perhaps an example would help.

**Comment by ClosetGeek-Git** [comment]
One example would be existing shims and pollyfills that can't be resolved using import. Not all useful javascript is distributed as a module. My reference to html is more a matter of a browsers javascript enfornment and how javascript is loaded into browser environments. This is the closest environment to quickjs as opposed to the standard server environments. "Browser" scripts which are _not_ modules are loaded into the browser <script src="baz"> which interprets everything at the global level. Such files can only be loaded into quickjs using std.loadscript().  This should be clear.

**Comment by ClosetGeek-Git** [comment]
It's basically the equivalent of dynamically creating a script tag in the dom in order to load a script from within a script.

**Comment by saghul** [comment]
Gotcha.

I think you could have a helper that uses tjs.readFile and then uses indirect eval() to evaluate it.

That's how loadFile is implemented in qjs.
