### ISSUE TITLE
Possible misinformation in PosixSocket read function

### ISSUE THREAD

**Issue by tokbuga** [saghul/txiki.js#451]
I'm not sure but i think socket object's read function get an array as a argument and returns number as bytes read. But documentation says reverse:

_i think:_
**_recv( Uint8Array ) : size_**

<img width="999" alt="image" src="https://github.com/saghul/txiki.js/assets/924685/c86c175f-f097-4a54-a96f-f06248ecd9ce">

https://bettercallsaghul.com/txiki.js/api/classes/global.tjs.PosixSocket.html#recv

Also, can i use sharedArrayBuffer as an backing store to collect read data; because i want to read continuously and write one big SharedArrayBuffer which sent by my javascript code -before txiki.js constructed PosixSocket object- and callbacks only offset and size information not full of buffer data; so i want to be fastest as i can. actually i had really hard work over years but i don't have friends who know this things because of my far far away living city erzurum. i really thankful if someone could help.

**Comment by saghul** [comment]
Nope, it gets a size and returns the data that was read in an array: https://github.com/saghul/txiki.js/blob/9cad93b8299cb61b6bcff081ac5a83b97c9d2404/src/posix-socket.c#L293

It could indeed be optimized to read into an existing array.

> Also, can i use sharedArrayBuffer as an backing store to collect read data; because i want to read continuously and write one big SharedArrayBuffer which sent by my javascript code -before txiki.js constructed PosixSocket object- and callbacks only offset and size information not full of buffer data; so i want to be fastest as i can.

You should be able to use that with the builtin `tjs.connect` API: https://bettercallsaghul.com/txiki.js/api/interfaces/global.tjs.Connection.html with that you can read and write to a given buffer you manage.

Any reason why you went for the low level posix socket API?

**Comment by tokbuga** [comment]
> 
> You should be able to use that with the builtin `tjs.connect` API: https://bettercallsaghul.com/txiki.js/api/interfaces/global.tjs.Connection.html with that you can read and write to a given buffer you manage.

thanks i just meet txiki.js and thanks for your hours.

> 
> Any reason why you went for the low level posix socket API?
yes, i'm working on an network device which has dhcp and dns services on it to make a captive enforced local network in lower costs. current solutions for captive portals is commonly more corporate friendly and third party users who shares their internet connections often need to protect theirselves too (someone who used their connection to spread misinformation which illegal for laws).

i made dhcp and dns services based on raw network data and now, i want to implement kind of cheap device like orangePI. So i need to save my device resources like memory or cpu, even network, hdd IO operations as much as i can.

i barely made an v8 module but i need more stability. i tried to escape dependencies until txiki.js. i think i will use to reach end. no need to be stubborn anymore :) here part of my c code (_i started turbopascal a lot of years agor but didn't write in C before because of it's ugly operators which there is no one here to tell what they doing everywhere_):

<img width="519" alt="image" src="https://github.com/saghul/txiki.js/assets/924685/f8c8f325-8d6a-4c91-a701-96bb571ea6b8">

i used (_manipulated_) [raw-socket](https://www.npmjs.com/package/raw-socket) module's c code.

**Comment by tokbuga** [comment]
> You should be able to use that with the builtin `tjs.connect` API: https://bettercallsaghul.com/txiki.js/api/interfaces/global.tjs.Connection.html with that you can read and write to a given buffer you manage.

i need to bound layer2 :/

**Comment by tokbuga** [comment]
how can i create an typed array from sharedarraybuffer with an offset and byte length; is there any documentation anywhere

**Comment by saghul** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array

`new Uint8Array(ab, byteOffset, length)`

**Comment by tokbuga** [comment]
in txiki.js :)
something like:

<img width="773" alt="image" src="https://github.com/saghul/txiki.js/assets/924685/fdacf3a3-56b6-4dd9-af6b-10dc27f78ed5">

**Comment by saghul** [comment]
Oh hehe yeah that would work!

**Comment by tokbuga** [comment]
sorry for you saghul, you really don't know whats going on this life
