### ISSUE TITLE
Can txiki be compiled into a WASM module?

### ISSUE THREAD

**Issue by dimisus** [saghul/txiki.js#452]
The project checks a lot of boxes in what I need, thank you for the library!

But I need `txiki.js` as a wasm module so I can run JS code against.

Is this possible?

**Comment by saghul** [comment]
> The project checks a lot of boxes in what I need, thank you for the library!

Good to hear, thank you!



> But I need `txiki.js` as a wasm module so I can run JS code against.
> 
> Is this possible?

Not easily I don't think. The JS engine powering `txiki.js` can `QuickJS`, but this project adds a lot more stuff there in terms of platform support, such as sockets, etc. It even embeds a small WASM engine itself.

I don't think it would be easy (os possible!) to have all of that working inside WASM.

**Comment by saghul** [comment]
Not sure. Everything you listed is "simple" except the FS access, because it would need to be written for WASI specifically.
