### ISSUE TITLE
Signals don't work if not bound to a variable

### ISSUE THREAD

**Issue by typeless** [saghul/txiki.js#476]
```
async function main() {
  //const h = tjs.signal('SIGINT', () => {
  tjs.signal('SIGINT', () => {
    console.log("SIGINT received");
    tjs.exit(0);
  });

  await new Promise((resolve) => { setTimeout(resolve, 10 * 1000) });
  console.log("done waiting");
}

await main();
```
When entering 'ctrl+c'
Expected output (when `tjs.singal(...)` replaced with `const h = tjs.signal(..)`)
```
^CSIGINT received
```
Actual output
```
^C
```

**Comment by saghul** [comment]
Yes, that's kinda by design.

The returned handle allows you to close the handler for example.

If it gets garbage collected, it will be auto-closed and removed.

Not sure how to best handle this without the potential for resource leaks.

**Comment by typeless** [comment]
Got it. That makes sense.
