### ISSUE TITLE
URL.createObjectURL

### ISSUE THREAD

**Issue by EmixamPP** [saghul/txiki.js#479]
Hey, I would like to ask your help concerning the missing `URL.createObjectURL` browser feature.

Here's some background, I would like to use the MQTT.js library (https://github.com/mqttjs/MQTT.js), which is compatible with browsers. However, I encountered two problems:
1. The lib detects whether it's in the browser by checking whether a `document` variable is defined in the global scope (because it is also compatible with Node.js by using the ws lib instead of "native" WebSocket). Thus I just added:
   ```
   Object.defineProperty(globalThis, 'document', {
    enumerable: true,
    get() {
        return globalThis;
    },
    set() {}
   });
   ```
   in the `src/js/polyfills/global.js` file
2. The lib requires the `URL.createObjectURL` https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static and `URL.revokeObjectURL` https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL_static functions

This is where I ask for your help, do you think there is a way to make this feature work in `txiki.js`?

Here is what I've tried (this is really naïve); I've added:
```
const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
function generateString(length) {
    let result = '';
    for (let i = 0; i < length; ++i) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}

URL.createObjectURL = (obj) => {
    const url = generateString(32);
    globalThis[url] = obj;
    return url;
};

URL.revokeObjectURL = (url) => {
    delete globalThis[url];
};
```
to `src/js/polyfills/url.js`

After that, the lib does not require additional feature, and even work in some way, but it logs the following error:
`ReferenceError: could not load '<the random string generated>' - ENOENT: no such file or directory`

**Comment by saghul** [comment]
I suspect the problem is that the URL represents a FIle or Blob, and it tries to read the file, which fails with a nu such file error.

Do you know where in mqtt.js the failure occurs?

**Comment by EmixamPP** [comment]
Correct, this is a Blob

I tried to find from where this code comes from, and it seems it is imported from the worker-timer lib: https://github.com/chrisguttandin/worker-timers The object url is created by this function:
https://github.com/chrisguttandin/worker-timers/blob/eb37969a7ac337be5a3fa332a951ffa30e2361db/src/factories/load-or-return-broker.ts#L1C1-L19C3

More generally, it concerns the lines 17491 to 17539 of the `mqtt/dist/mqtt.js` file that you can consult through the browser here: https://www.npmjs.com/package/mqtt?activeTab=code (or you have to execute `npm install mqtt`)
If we look at the line 17518: `var loadOrReturnBroker = createLoadOrReturnBroker(workerTimersBroker.load, worker);`
we can conclude that this is the `workerTimersBroker.load` function that will load the object url. However, I was not able to determine what is the `workerTimersBroker` argument.

And somehow, if think these lines are linked to this source file of the MQTT.js https://github.com/mqttjs/MQTT.js/blob/main/src/lib/get-timer.ts But that's hard to determine because it is bundled

**Comment by EmixamPP** [comment]
After further analysis, the generated blob object url is passed as argument to a `new Worker(url)` object

**Comment by saghul** [comment]
Got it. Looks like txiki.js would need to implement a Blob store so those URLs are mapped to something that other APIs can read.

I see Deno has it, we could borrow some inspiration from there...

**Comment by KaruroChori** [comment]
For reference: https://github.com/saghul/txiki.js/issues/545#issuecomment-2162699222

**Comment by EmixamPP** [comment]
I'm working on a simple solution. I should PR in the coming days. But I would need review/help for sure to improve the quality of the solution.

**Comment by saghul** [comment]
Sure thing!
