### ISSUE TITLE
Making SQLITE exclude-able via build flag

### ISSUE THREAD

**Issue by lal12** [saghul/txiki.js#486]
Would like to make sqlite3 exclude-able via build flag. It increases final binary size by 1M (stripped).

**Comment by lal12** [comment]
Hmm, just saw that sqlite is used in storage class. So it's probably not a good idea.

**Comment by saghul** [comment]
Yeah and I plan to implement REPL history on top of it.

Making all of that optional doesn't sound like a good time :-/ 

Is the size increase a big problem in your environment?

**Comment by lal12** [comment]
> Is the size increase a big problem in your environment?

Practically not really, more of colleagues complaining it isn't 10Kb of assembler :sweat_smile:

**Comment by lal12** [comment]
Though too add to that: Just from a very general standpoint: having a lightweight and small engine like txiki.js obviously is the key point otherwise "why not node". So having a component (which apart from when you actually need sqlite) which just does very simple things like the REPL history and a simple key value store, but needing 20% of your binary size isn't the best price-performance ratio.

Not saying it would be worth the effort to change it now nor wanting to, just me sharing a thought.

**Comment by saghul** [comment]
That's a fair point. I think that number will decrease when mbedtls and lws are added since those are the 2 big libraries "missing".

Another option is to go the shared library route, so the base txiki.js is smaller... but I'd rather have a self-contained single binary, at least for the time being.
