### ISSUE TITLE
Strange behaviour with jscallbacks

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#506]
I would assume this code to work properly:
```
const cb = new ffi.JSCallback(ffi.types.sint64, [], () => { return 42 })
const fn = new ffi.CFunction(libffi.symbol('testcb'), ffi.types.void, [ffi.types.jscallback])
fn.call([cb])
```
however an exception `Error: not a JSCallback` is returned. The more explicit version:
```
const cb = new ffi.JSCallback(ffi.types.sint64, [], () => { return 42 })
const fn = new ffi.CFunction(libffi.symbol('testcb'), ffi.types.void, [ffi.types.pointer])
fn.call([cb.addr])
```
it works as expected.

The C function is:
```
void testcb(long int (*cb)()) {
    long int val  = cb();
    printf("Hello %ld\n",val);
}
```

Is there any basic misunderstanding on how callbacks are supposed to be used on my end?

**Comment by saghul** [comment]
Ping @lal12

**Comment by KaruroChori** [comment]
By the way, there is also something quite suspicious happening @ https://github.com/saghul/txiki.js/blob/master/src/js/stdlib/ffi/ffi.js

```
    [ types.uint32, [ 'uint32_t', 'signed long long', 'signed long long int', 'long long', 'long long int' ] ],
```
Does not seems right, unless there are strange reasons behind this choice.

**Comment by KaruroChori** [comment]
My mistake! It should have been `cb` and not `[cb]`. The variadic magic was interfering a bit with types.
