### ISSUE TITLE
No support for sql transactions in tjs:sqlite

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#511]
Most query builders and ORM libraries assume there is support for transactions on the database driver.  
From what I can tell this is missing from the custom integration of txiki.

Such change would meaningfully improve the ecosystem of libraries which can be made to work with this runtime.

**Comment by saghul** [comment]
Absolutely! I strated with the bare minimum, with the intention to complete things at a later stage.

Do you have an API in mind we can go over? I got heavily inspired by Bun's when made the txiki.js module.

**Comment by KaruroChori** [comment]
Both better-sqlite3 & bun provide support for transactions, so doing something more or less in line with their implementation would be best in my opinion.
Mostly because the process of integrating dirzzle/kysely/prisma/whatever at that point is just a bit more effort than copy&paste :D.

**Comment by saghul** [comment]
Got it 👍  No ETA at the moment, but it's certainly close in the roadmap.

**Comment by KaruroChori** [comment]
Btw, a lot of libraries I tried were not compatible because of https://github.com/bellard/quickjs/issues/261 which has been just merged to quickjs. What is the general process for patches/fixes in this repo? quickjs <-> quickjs-ng -> txiki.js?

**Comment by saghul** [comment]
I'll port the fox to NG, then bump it here.
