### ISSUE TITLE
AF_UNIX  missing in namespace tjs

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#512]
Unlike other socket related constants, this is missing.
In general it seems like the library is only focusing on the INET family.

Still, Unix Domain Sockets are working as expected once properly configured, so there is no specific reason to not support them I think.

Also, it would be nice to have js helpers to construct the addr structs.
At the moment we are forced to manually construct the Uint8Array, which works but it is a bit inconvenient.
In case, I can do it.

**Comment by lal12** [comment]
I didn't implemented a helper and the constant because it seemed more useful to use the normal streaming tjs socket for that. It was a generic implementation for any kind of sockets. E.g. I use it for raw sockets.

**Comment by lal12** [comment]
What's your application using the PosixSocket btw?

**Comment by KaruroChori** [comment]
I am using a file via UNIX Domain Sockets in streaming mode to share information with limited overhead between local processes and with external clients via a websockets bridge.

**Comment by saghul** [comment]
Any reason not to use the builtin `conect` https://bettercallsaghul.com/txiki.js/api/functions/global.tjs.connect.html ? The `pipe` transport is unix sockets.

**Comment by KaruroChori** [comment]
I am not sure I am following. The builtin connect is built around AF_INET, requiring an address and port. IPC with Unix Domain Sockets uses a filename as address, The socket address type is not the same.

To explain it better, I was forced to write something like

```
	const sock = new PosixSocket(1, tjs.SOCK_STREAM, 0);
	const addr = new Uint8Array(110);
	addr[0] = 1;
	Array.from("../test-file").map(
		(letter, i) => (addr[2 + i] = letter.charCodeAt(0)),
	);

	sock.bind(addr);
```
It should be
```
	const sock = new PosixSocket(AF_UNIX, tjs.SOCK_STREAM, 0);
	const addr = somehelperfunction('../test-file')
	sock.bind(addr);
```

**Comment by saghul** [comment]
It's a normal Unix domain socket, represented by a file.

Abstract sockets are not currently supported.

**Comment by KaruroChori** [comment]
Yes, I was not planning on using them.
Just be clear, I assume there is no reason for them to work via posix-stream.
You are just saying they are not supported by the higher level stream implementation you are providing, right?

**Comment by saghul** [comment]
It would be nice if they work in the low level, I guess @lal12 didn't implement them because it wasn't necessary at the time.

In general the high level implementation is preferred, as it's cross-platform.

**Comment by KaruroChori** [comment]
As far as I know, the abstract variant is a linux specific extension. So it is unlikely they can be made cross-platform, but I don't know enough about windows to tell.

Also, my understanding from the code is that pipes are assuming a stream-based connection. However Unix Domain Sockets would also allow for packet and sequence packet in place of SOCK_STREAM.

**Comment by saghul** [comment]
> As far as I know, the abstract variant is a linux specific extension. So it is unlikely they can be made cross-platform, but I don't know enough about windows to tell.

I mean Unix sockets / windows named pipes, not the abstract variant specifically.



> Also, my understanding from the code is that pipes are assuming a stream-based connection. However Unix Domain Sockets would also allow for packet and sequence packet in place of SOCK_STREAM.

Correct, I missed to point that out. The libuv API which txiki.js wraps is only for streams.

**Comment by KaruroChori** [comment]
I see. In principle, would you accept PR on what discussed so far?

More in general, is there any roadmap or policy on what is suitable for this project and what is not, aside from what reported in https://github.com/saghul/txiki.js/issues/418?

I am extending txiki quite a bit since I am adopting it as the runtime for an embedded application. A few of these features would make sense to be here in upstream, but without discussions enabled in this repo I would have to abuse *pr* or *issues*.

**Comment by KaruroChori** [comment]
No problem going by feeling, I just wanted to make sure I was not missing anything obvious as I usually do :D.
Great, thank you!

**Comment by saghul** [comment]
I believe this one if fixed now, right?

**Comment by lal12** [comment]
> I believe this one if fixed now, right?

No, AF_UNIX isn't exposed if you mean that.
But I think it might be useful for opening DGRAM unix sockets or abstract unix sockets. I currently just define AF_UNIX myself. But exposing it is probably more useful. Will create a PR.
