### ISSUE TITLE
Poll with SOCK_STREAM sockets

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#513]
While ~`socket.pool`~  `socket.poll` works in conjunction with SOCK_DGRAM sockets, I have not been able to make it work in the context of stream connections (blocking listening / accepting / reading works, I tested it).

Do you know if the relevant functionality is implemented?
I checked in the testsuite but there is only one where example and SOCK_DGRAM is used.
I checked the library code and there is not much screaming "I don't work with sockets" but I am not familiar with libuv, so I cannot tell for sure.

**Comment by KaruroChori** [comment]
I found the issue. Basically PosixSocket!=PosixSocket. There is an aliasing problem as we have the PosixSocket js class, and the one part of core. While they share most of the interface, and so they have been exposed interchangebly with the same typescript type, two functions have very different prototypes: `pool` and `stopPool`

```
static JSValue tjs_sock_poll(JSContext *ctx, JSValue this_val, int argc, JSValue *argv)
```

```
poll(cbs)
```

The socket returned by `accept` is of the core type, so read will work, but the two pool function cannot. Copying the implementation in the class PosixSocket to wrap the c struct will make it work.

Proposals for solution:
- Accept should return a JS PosixSocket fat object.
- The two types are fully split.

**Comment by saghul** [comment]
Ping @lal12

**Comment by KaruroChori** [comment]
> Btw what exactly do you mean by `socket.pool`?

I meant that my brain was being silly, and was unable to consider `poll` and `pool` as two different words :D.

**Comment by lal12** [comment]
> > Btw what exactly do you mean by `socket.pool`?
> 
> I meant that my brain was being silly, and was unable to consider `poll` and `pool` as two different words :D. I fixed those messages so that they don't confuse anyone else.

:D just was confused  because socket pools can be a thing too.

**Comment by KaruroChori** [comment]
@lal12 thanks for the fix!
