### ISSUE TITLE
Small UX inconvenience when running on embedded Linux via serial console

### ISSUE THREAD

**Issue by typeless** [saghul/txiki.js#521]
Currently, when running tjs via serial console, where the controlling terminal points to a physical UART serial port, tjs always hangs at the call to `openat` to the same tty.

![image](https://github.com/saghul/txiki.js/assets/2606021/6dde53fc-ecde-4f5e-a1b4-140b2a8aa913)

It works fine when the console is not activated (launched by a GUI or something else like a boot script).
It can also be worked-around by redirection such as `tjs </dev/tty >/dev/tty 2>/dev/tty`. But it's a bit awkward with regard to DevX.

**Comment by saghul** [comment]
I think this is a libuv feature. It reopens the std fds if they point to a tty so all mode changes can be reversed.

I'm afraid we don't have much control over that.

Is there a way to detect that kind of tty?

**Comment by typeless** [comment]
>Is there a way to detect that kind of tty?
I have no idea.

It does seem to be serial driver specific. I tried to reproduce the problem by logging in the console via a USB CDC/ACM port, it didn't exhibit the same behavior. 
I'll see if there is something I can do. Thanks.

![image](https://github.com/saghul/txiki.js/assets/2606021/b69fa0d3-2f32-4337-b5e2-832329346c56)
