### ISSUE TITLE
Release of @txikijs/types for `next` version

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#547]
It would be helpful to distribute the npm package with all types aligned with the latest main branch.  
Probably tagged as `beta` or `next`.

For context, I am adding a new driver in [drizzle](https://github.com/drizzle-team/drizzle-orm) to work with txiki. Without aligned types it would be impossible to distribute it and PR it in the main repo.

**Comment by saghul** [comment]
Types are released when a new release is made. I'll try to get one out this week.

**Comment by KaruroChori** [comment]
For reference, https://github.com/drizzle-team/drizzle-orm/pull/2551 is a PR to merge support in txiki to the drizzle main branch. This is not likely to happen as it is not justified by a wide enough user base, but I needed it for my project so there it is.
