### ISSUE TITLE
lint: 'URLPattern' is not defined

### ISSUE THREAD

**Issue by EmixamPP** [saghul/txiki.js#581]
When using `URLPattern` inside a polyfill (like in #548), `npm run lint` raise a false-positive error on it:

```
$ npm run lint --fix

> txiki.js@0.0.0 lint
> eslint --max-warnings 0 .


/home/maxime/txiki.js/src/js/polyfills/worker.js
  36:31  error  'URLPattern' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

This could be probably also the case for other symbols inside the `globalThis`

**Comment by saghul** [comment]
It's possible that happens, but it's a false positive. By the time the worker constructor code runs it will be defined. Perhaps an eslint update will fix it?

For the time being, add some eslint-ignore coment, since we know it works.

**Comment by EmixamPP** [comment]
Feel free to close
