### ISSUE TITLE
Function to clear the session memory in repl

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#582]
I just noticed there is now persistent memory for past commands in the repl, which is great.
It would be nice to have a helper function to also clear its content. `\clear` only affects the command line.
Maybe it is already there and I was not able to find it.

**Comment by saghul** [comment]
It's not there, I planned to add it later :-P

Do you think a `\clear-history` command is best, or to drop entries, effectively capping the history size to N?

**Comment by KaruroChori** [comment]
I think an explicit `\clear-history` is best. An arbitrary cap without further configuration could be confusing.
There is room for more features thanks to this persistent sqlite storage, like saving a past session as file. Or storing secrets like auth tokens, caching blobs...
