### ISSUE TITLE
Repl is always returning additional line

### ISSUE THREAD

**Issue by KaruroChori** [saghul/txiki.js#623]
Many repl operation will also return an additional `> undefined` line when not desirable. For example
```
> console.log('Hello')
Hello
> undefined
```

**Comment by saghul** [comment]
The hat is expected of the REPL because it's the return code of the previous line.

IIRC Node, Deno and Bun do it. The o my one I think doesn't could be Python, if the return value is None.

**Comment by KaruroChori** [comment]
Fair, but all the other repl environments are not showing the `>` which implies some kind of action from the user.

**Comment by saghul** [comment]
That could be fixed yes!
