### ISSUE TITLE
Encoding not supported. Only utf-8 is supported

### ISSUE THREAD

**Issue by ahaoboy** [saghul/txiki.js#630]
There are many libraries that use ``` new TextDecoder("utf8")```

https://github.com/arv/text-encoding-utf-8/issues/4

An alternative library is text-decoding, but it is 500k
https://github.com/idiocc/text-decoding

**Comment by saghul** [comment]
Our TextEncoder/Decoder implementation only supports UTF8.

I have no plans to change this since it adds a significant chunk to our bundle size.

Do you get a problem when instantiating it with that name?

**Comment by ahaoboy** [comment]
> Do you get a problem when instantiating it with that name?

Both of these are valid utf8 formats, some libraries mix the two and cause errors

```
new TextDecoder("utf8")

new TextDecoder("utf-8")
```

text-encoding-utf-8 is no longer maintained, so it can only be fixed by patch or polyfill. This is my current temporary solution
```
import { TextEncoder, TextDecoder as BaseTextDecoder } from 'text-encoding-utf-8';

window.TextEncoder = TextEncoder;
window.TextDecoder = class TextDecoder extends BaseTextDecoder {
  constructor(encoding, options) {
    encoding = String(encoding).toLowerCase()
    encoding = encoding === 'utf8' ? 'utf-8' : encoding
    super(encoding, options)
  }
};
```

**Comment by KaruroChori** [comment]
Looking at the specs reported in the issue you linked, while there might be some slight differences amongst those entries, for maximum compatibility we should just provide any of the following as alias names for utf8:
```
"unicode-1-1-utf-8"
"unicode11utf8"
"unicode20utf8"
"utf-8"
"utf8"
"x-unicode20utf8" 
```
It would require no further effort on the encoding/decoding side.

**Comment by ahaoboy** [comment]
> It would require no further effort on the encoding/decoding side.


There are indeed many aliases, but I have only encountered utf8 and utf-8 
It may also be due to the optimization of the bundle tool? utf8 will have one less character than utf-8

**Comment by KaruroChori** [comment]
I think this has more to do with the fact we had breaking changes to the encoding between unicode 1.1 and 2. 
If memory serves me right, the hangul from korean were changed places (breaking) and tibetan was first removed and later reintroduced.

So documents encoded in those years for these respective languages are a mess to handle, unless they have been later re-encoded.
Realistically it means that "unicode-1-1-utf-8" and "unicode11utf8" should be explicitly skipped from those supported unless we know for sure the underlying polyfill is capable of handling them (likely not).

My understanding is that utf8/utf-8 are totally equivalent, and they are just supersets of utf8 rev 2 aligned with later extensions.

>  It may also be due to the optimization of the bundle tool? utf8 will have one less character than utf-8

Not sure if that is the case. Still we have multiple names for the same or very closely related encodings so I agree with you support for both should be added.
