### ISSUE TITLE
new Uint8Array(65536) throws "too many arguments in function call (only 65535 allowed)""

### ISSUE THREAD

**Issue by guest271314** [saghul/txiki.js#631]
Steps to reproduce https://github.com/guest271314/native-messaging-txiki.js.

On https://github.com/guest271314/native-messaging-txiki.js/blob/main/nm_tjs.js#L8

Substitute 

```
  const buffer = new Uint8Array(65536);
```

for 

```
  const buffer = new Uint8Array(65535);
```

and include on line 51 to send the error message to the browser in `catch`.

```
    sendMessage(new TextEncoder().encode(JSON.stringify(e.message)));
```

**Comment by KaruroChori** [comment]
Is it not just a hard limit to 16 bits somewhere?

**Comment by saghul** [comment]
Weird! Can you reproduce that with QuickJS-ng directly?

**Comment by bnoordhuis** [comment]
Yes, it's a quickjs limitation, controlled by JS_MAX_LOCAL_VARS in quickjs.c.

**Comment by saghul** [comment]
Yeah and I think there is a test that creates a huge array to check the memory limit too...

**Comment by bnoordhuis** [comment]
The problematic line in OP's example is the splat at https://github.com/guest271314/native-messaging-txiki.js/blob/850dc83684eee7493652832ba8e95121027b517f/nm_tjs.js#L15C5-L15C40:
```js
    data.push(...buffer.subarray(0, n));
```
With a big enough buffer you go over JS_MAX_LOCAL_VARS (which is indeed 65,535) but that's not a bug, just an engine limitation. Compare V8: it has (or had) an upper limit of 262,144 arguments.

**Comment by KaruroChori** [comment]
I cannot test it right now, but might it be this?
```
    data.push(...buffer.subarray(0, n));
```
If `n` gets too big, you get a push of over 16 bits. This might exceed some limits set in the engine. It is not a problem about the Uint8Array itself, but the way it is passed via push maybe.

**Comment by KaruroChori** [comment]
Lol, it looks like both @bnoordhuis and me reached the same conclusion.

**Comment by guest271314** [comment]
> Weird! Can you reproduce that with QuickJS-ng directly?

With QuickJS-ng we don't have to do any of this.

QuickJS is the only JavaScript engine/runtime that I have tested that reads standard input to completion in one (1) read.

QuickJS is also the fastest to read standard input between `tjs`, `node,` deno`, `bun`, and to the extent applicable, SpiderMonkey's `js` and V8's `d8`.

```
function getMessage() {
  const header = new Uint32Array(1);
  std.in.read(header.buffer, 0, 4);
  const output = new Uint8Array(header[0]);
  std.in.read(output.buffer, 0, output.length);
  return output;
}
```

1. QuickJS `0.13219999998807908`
2. Bun `0.23210000002384185`
3. Deno `0.2816999999880791`
4. Node.js `0.3367000000476837`
5. Mozilla SpiderMonkey `js` shell `0.49760000002384186`
6. Google V8 d8 shell (Using a Bash script for reading `stdin` with `dd` and `od`) `0.5716999999880791` 
7. txiki.js `0.695`
8. Google V8 `d8` shell (Using QuickJS for reading `stdin`) `0.9368999999761581`

V8's `d8` doesn't really read `stdin` at all, rather appears to try ot *execute* input with `readline()`, so ironically I use QuickJS (-ng) or `dd` command in a Bash script to read standard input to `d8` then send `stdin` back to `d8` at https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_d8.js#L9-L31 

```
function getMessage(pid, [command, argv]) {
  try {
    const stdin = (os.system(command, argv)).trim();
    if (stdin != undefined && stdin != null && stdin.length) {
      const cmd = command.split(/[/-]/).pop();
      if (cmd === "bash") {
        const message = encodeMessage(stdin);
        return message;
      }
      if (cmd === "qjs") {
        const data = encodeMessage(stdin);
        const view = new DataView(data.subarray(0, 4).buffer);
        const length = view.getUint32(0, true);
        // sendMessage(encodeMessage(JSON.stringify({ length })));
        return data.subarray(4, 4 + length);
      }
    } else {
      quit(1);
    }
  } catch (e) {
    writeFile("getMessageError.txt", encodeMessage(e.message));
  }
}
```

and https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_d8.js#L45-L102
```
  // readline() doesn't read past the Uint32Array equivalent message length
  // V8 authors are not interested in reading STDIN to an ArrayBuffer in d8
  // https://groups.google.com/g/v8-users/c/NsnStT6bx3Y/m/Yr_Z1FwgAQAJ
  // Use dd https://pubs.opengroup.org/onlinepubs/9699919799/utilities/dd.html
  // or GNU Coreutils head https://www.gnu.org/software/coreutils/manual/html_node/head-invocation.html
  // or QuickJS https://bellard.org/quickjs/
  const bash = ["bash", [
    "--posix",
    "-c",
    `
length=$(dd iflag=fullblock oflag=nocache conv=notrunc,fdatasync bs=4 count=1 if=/proc/${pid}/fd/0 | od -An -td4 -)
message=$(dd iflag=fullblock oflag=nocache conv=notrunc,fdatasync bs=$((length)) count=1 if=/proc/${pid}/fd/0)
printf "$message"
`,
  ]];
  const qjs = ["/home/user/bin/qjs", [
    "--std",
    "-m",
    "-e",
    `const path = "/proc/${pid}/fd/0";
  try {
    const size = new Uint32Array(1);
    const err = { errno: 0 };
    const pipe = std.open(
      path,
      "rb",
      err,
    );
    if (err.errno !== 0) {
      throw std.strerror(err.errno);
    }
    pipe.read(size.buffer, 0, 4);
    // writeFile("len.txt", size);
    // {error: 'writeFile is not defined'
    const output = new Uint8Array(size[0]);
    pipe.read(output.buffer, 0, size[0]);
    const res = new Uint8Array([...new Uint8Array(size.buffer),...output]);
    std.out.write(res.buffer, 0, res.length);
    std.out.flush();
    std.exit(0);
  } catch (e) {
    const json = JSON.stringify({error:e.message});
    std.out.write(Uint32Array.of(json.length).buffer, 0, 4);
    std.out.puts(json);
    std.out.flush();
    std.exit(0);
  }
`,
  ]];
  while (true) {
    // Terminate current process when chrome processes close
    if (!(os.system("pgrep", ["-P", JSON.parse(ppid)]))) {
      break;
    }
    const message = getMessage(
      pid,
      qjs,
    );
```

> The problematic line in OP's example is the splat at https://github.com/guest271314/native-messaging-txiki.js/blob/850dc83684eee7493652832ba8e95121027b517f/nm_tjs.js#L15C5-L15C40:
> 
> ```js
>     data.push(...buffer.subarray(0, n));
> ```
> 
> With a big enough buffer you go over JS_MAX_LOCAL_VARS (which is indeed 65,535) but that's not a bug, just an engine limitation. Compare V8: it has (or had) an upper limit of 262,144 arguments.

That's it. 

My initial prospective fix was something like the following using Iterator Helpers, tested in Chromium 128. 

```
var arr = [];
arr.push(new Uint8Array([1,2,3]).values().toArray());
arr.push(new Uint8Array([4,5,6]).values().toArray());
arr.flat();
```

`tjs` throws

```
> var u = new Uint8Array([1,2,3])
> undefined
> u.values()
> Array Iterator {  }
> u.values().toArray()
> TypeError: not a function
    at <eval> (<evalScript>:1:1)
    at evalScript (native)
    at eval_and_print (run-repl.js:14:35)
    at handle_cmd (run-repl.js:20:1)
    at readline_handle_cmd (run-repl.js:19:121)
    at handle_key (run-repl.js:10:2079)
    at handle_char (run-repl.js:10:1630)
    at handle_byte (run-repl.js:1:2128)
    at initialize (run-repl.js:1:2065)

```

So for now I'm just iterating the subarray and pushing each value. 

```
async function readFullAsync(length) {
  const buffer = new Uint8Array(65536); // too many arguments in function call (only 65535 allowed) 
  const data = [];
  while (data.length < length) {
    const n = await tjs.stdin.read(buffer);
    if (n === null) {
      break;
    }
    for (const value of buffer.subarray(0, n)) {
      data.push(value);
    }
  }
  return new Uint8Array(data);
}
```

Thanks all.
