### ISSUE TITLE
repl history doubles in size on each run

### ISSUE THREAD

**Issue by undernorthernsky** [saghul/txiki.js#662]
```
$ rm ~/.tjs/history.db
$ ./build/tjs 
Welcome to txiki.js - Type ".help" for help
> a
> b
> c

$ echo 'select count(*) from history' | sqlite3 ~/.tjs/history.db 
3

# start & exit repl multiple times

$ ./build/tjs 
$ echo 'select count(*) from history' | sqlite3 ~/.tjs/history.db 
6

$ ./build/tjs 
$ echo 'select count(*) from history' | sqlite3 ~/.tjs/history.db 
12
```

Closing the repl quickly becomes noticeably slower; a quick hack is
to batch the inserts to avoid O(n) fsync calls.

``` 
     function save_history() {
         if (historyDb) {
-            for (const str of history) {
-                try {
-                    historyDb.prepare('INSERT INTO history (entry) VALUES(?)').run(str);
-                } catch (_) {}
-            }
+            const insert = historyDb.prepare('INSERT INTO history (entry) VALUES(?)');
+            const insertMany = historyDb.transaction(entries => {
+              for (const str of entries) {
+                insert.run(str);
+              }
+            });
+            insertMany(history);
```

Of course this doesn't fix the root cause; remember history length on load and only save `history.slice(initial_length)`?

**Comment by undernorthernsky** [comment]
or maybe:
- delete from history
- batch insert
- vacuum

**Comment by saghul** [comment]
> Closing the repl quickly becomes noticeably slower; a quick hack is
> to batch the inserts to avoid O(n) fsync calls.

This makes sense indeed!



> Of course this doesn't fix the root cause; remember history length on load and only save `history.slice(initial_length)`?

And this too, good catch!

Would you like to send a PR?

**Comment by undernorthernsky** [comment]
Sure.

- so far haven't updated `run-repl.c`; was afraid that might depend on my environment (node version)? though it was the only changed file; is that safe to do?
- no idea about a unit test; tested manually, everything looks ok

---

btw: do you have any pointers on building `libtjs.a` with a reduced feature set / dependencies?

easy enough to conditionally skip some sources in cmake; but no idea how to proceed when e.g. the transpiled js->c code depends on an excluded `mod_foo.c`.

probably not possible in the upstream project, so fork and modify the build?

**Comment by saghul** [comment]
In order to update the bundled code you need to "make js" and that should do.

What features would you like to skip?

**Comment by undernorthernsky** [comment]
Actually most of them :-)
My current experiment only needs fetch (curl), local fs & pipes (uv); not really a problem to hack this myself.

In general explicit control over what apis are available when embedding libtjs for specific use cases; exposing libffi & network sockets to potentially untrusted code…

Really a nice to have; I don't see how this kind of modularity can be (easily) done as a compile time option.
Was just wondering if you have any ideas; "out of scope" is a valid answer.

**Comment by saghul** [comment]
I believe it would be a bit hard to add the flexibility, but if you have ideas I'd be happy to hear and consider them.

The main hurdle, I think is that even if we hide some APIs from the `tjs` global, it's still possible to reach the core with the global internal symbol name.

You are not the first to ask though, so I wonder if there is a way to get there without very invasive changes... 🤔
