### ISSUE TITLE
Allow Explicitly Running/Not Running Code as a Module

### ISSUE THREAD

**Issue by TheBrokenRail** [saghul/txiki.js#77]
Like ```--module```/```-m``` and ```--no-module```

**Comment by saghul** [comment]
Honest question: what’s your use case here? I was considering enabling module support explicitly if the extension mjs is used and otherwise using the builtin detection heuristics (as it does now).

**Comment by TheBrokenRail** [comment]
I want it to be clear in my application that JS files are not modules, and MJS files are modules, and to do that I need a way to always run JS files as non-modules and MJS files as modules. Maybe it would make more sense to instead add a ```--strict-modules``` or something else to tell txiki.js it should only run it as module code if its extension is MJS.

________________________________

**Comment by TheBrokenRail** [comment]
I want it to be clear in my application that JS files are not modules, and MJS files are modules, and to do that I need a way to always run JS files as non-modules and MJS files as modules. Maybe it would make more sense to instead add a ```--strict-modules``` or something else to tell txiki.js it should only run it as module code if its extension is MJS.

**Comment by saghul** [comment]
I see. I'll give this some thought.
