### ISSUE TITLE
Add addEventListener to XHR

### ISSUE THREAD

**Issue by TheBrokenRail** [saghul/txiki.js#78]

**Comment by saghul** [comment]
Makes sense, I’ll take a similar approach to Worker here: the C module only does callbacks and the JS one implements EventTarget.

**Comment by TheBrokenRail** [comment]
Any update on this?

**Comment by saghul** [comment]
I'm on it, but haven't had much time these days alas. I hope to get it done this week or so.

**Comment by TheBrokenRail** [comment]
Any updates? @saghul

**Comment by saghul** [comment]
Sorry I haven’t been able to finish it before going on the xmas break and now my laptop with the WIP is in a different country :-/

**Comment by TheBrokenRail** [comment]
Any updates? @saghul
