### ISSUE TITLE
Allow overriding filename in errors from CLI

### ISSUE THREAD

**Issue by TheBrokenRail** [saghul/txiki.js#79]

**Comment by saghul** [comment]
Can you clarify?

**Comment by TheBrokenRail** [comment]
Allow overriding the filename that is shown in error messages with ```--filename hello.js```, I want to use this because what the file is stored as in the filesystem may not always match what should be shown to the user.

________________________________

**Comment by TheBrokenRail** [comment]
Allow overriding the filename that is shown in error messages with ```--filename hello.js```, I want to use this because what the file is stored as in the filesystem may not always match what should be shown to the user.

**Comment by saghul** [comment]
I see. Does any other runtime implement this? Off the top of my head, I have never run into this need, so I'm curious!

**Comment by saghul** [comment]
I’ll keep this open, but I’m not very keen on having it. It seems like an edge case to me, and not something I am willing to support.
