### ISSUE TITLE
Request for FFI support

### ISSUE THREAD

**Issue by lygstate** [saghul/txiki.js#85]

**Comment by saghul** [comment]
I have this on the TODO list, but I’m thinking that it might be better to just add WAAM / WASI support instead, and have that be The Way ti access other libraries.

**Comment by saghul** [comment]
Note to self: https://github.com/ratboy666/qjs-ffi

**Comment by saghul** [comment]
https://github.com/shajunxing/quickjs-ffi

**Comment by saghul** [comment]
Just landed in master!
