### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by feng92f** [saghul/txiki.js#86]
I want to build a binary. but I dont know how to do it. qjsc -o doest not give me binary. 
so how to use txiki.js?

**Comment by saghul** [comment]
txiki.js uses QuickJS, but it's a module you can compile with it. Please follow the building instructions on the README: https://github.com/saghul/txiki.js#building

**Comment by feng92f** [comment]
@saghul so I delete repl.js, and make a new application?

**Comment by saghul** [comment]
No. txiki.js is like Node or Deno. You create your own JS files and it will run them. Of course the builtin stadliob is not as complete as the other two! :-)

**Comment by feng92f** [comment]
@saghul ok i got it, thanks.
