### ISSUE TITLE
building  on windows

### ISSUE THREAD

**Issue by feng92f** [saghul/txiki.js#89]
i encounter this error:

# make

cd build; cmake ../ -DCMAKE_BUILD_TYPE=Release
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/qjs/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/Desktop/qjs/build/CMakeFiles/CMakeError.log".

**Comment by feng92f** [comment]
it passed after i installed the Visual Studio

**Comment by saghul** [comment]
👍👍
